### ISSUE TITLE
Move types under features

### ISSUE THREAD

**Issue by loyd** [Alexhuszagh/i256-rs#62]
I see the new version of this crate provides not only `i256`(and the `I256` alias) but also `I384`, `I512` and `I1024`.

It would be nice to move all additional types under features to avoid increasing compilation time when they aren't used. WDYT?

Btw, they can be marked in the documentation with
```rust
#![cfg_attr(docsrs, feature(doc_cfg))]
#![cfg_attr(docsrs, feature(doc_auto_cfg))]
```
and
```toml
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
```

because docsrs compiles documentation using the nightly compiler.
